//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageDormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardingBill
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime date_founded { get; set; }
        public decimal total { get; set; }
        public string student_id { get; set; }
        public string note { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
