//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageDormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricityWaterBill
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime date_founded { get; set; }
        public int old_power_indicator { get; set; }
        public int new_power_indicator { get; set; }
        public Nullable<double> amount_electricity_consumed { get; set; }
        public Nullable<int> old_water_index { get; set; }
        public Nullable<int> new_water_index { get; set; }
        public Nullable<int> amount_water_consumed { get; set; }
        public decimal electricity_money { get; set; }
        public decimal water_money { get; set; }
        public decimal environmental_charges { get; set; }
        public decimal into_money { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string room_id { get; set; }
        public string note { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
