//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageDormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.BoardingBills = new HashSet<BoardingBill>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public bool gender { get; set; }
        public System.DateTime birthdate { get; set; }
        public string address { get; set; }
        public string citizen_identification { get; set; }
        public Nullable<System.DateTime> date_issue { get; set; }
        public string place_issue { get; set; }
        public string school { get; set; }
        public string course { get; set; }
        public string industry { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string room_id { get; set; }
        public Nullable<System.DateTime> contract_signing_date { get; set; } = DateTime.Now;
        public string avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardingBill> BoardingBills { get; set; }
        public virtual Room Room { get; set; }
    }
}
